examples/RazorPagesAndMvc/Controllers/Java/AdvancedJavaController.cs
using Microsoft.AspNetCore.Mvc;
using SmartBreadcrumbs.Attributes;

namespace RazorPagesAndMvc.Controllers.Java
{
    [Route("Java/Advanced/[action]")]
    public class AdvancedJavaController : Controller
    {
        [HttpGet]
        [Breadcrumb("Advanced", FromAction = "Index", FromController = typeof(JavaController))]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Breadcrumb("Advanced", FromAction = "Index", FromController = typeof(JavaController))]
        public IActionResult Index(int i)
        {
            return View();
        }

        [HttpGet]
        [Breadcrumb("Post 1", FromAction = "Index")]
        public IActionResult Post1()
        {
            return View();
        }

    }
}

examples/RazorPagesAndMvc/Controllers/Other/OtherController.cs
using Microsoft.AspNetCore.Mvc;
using RazorPagesAndMvc.Pages.CSharp;
using SmartBreadcrumbs.Attributes;

namespace RazorPagesAndMvc.Controllers.Other
{
    [Route("Other/[action]")]
    public class OtherController : Controller
    {

        [Breadcrumb("<script>alert('test')</script>", FromPage = typeof(IndexModel))]
        public IActionResult XssTest()
        {
            return View();
        }

    }
}

examples/RazorPagesAndMvc/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace RazorPagesAndMvc.Pages
{
    [Breadcrumb("About")]
    public class AboutModel : PageModel
    {

        public void OnGet()
        {
        }

    }
}

examples/RazorPagesAndMvc/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesAndMvc.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

examples/RazorPagesAndMvc/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace RazorPagesAndMvc.Pages
{
    [DefaultBreadcrumb("Index Page")]
    public class IndexModel : PageModel
    {

        public void OnGet()
        {

        }

    }
}

examples/RazorPagesAndMvc/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesAndMvc.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

examples/RazorPagesAndMvc/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

examples/RazorPagesAndMvc/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Index</h1>

<ul>
    <li>
        Index
        <ul>
            <li>
                <a asp-page="/CSharp/Index">C# - CSharp</a>
                <ul>
                    <li>
                        <a asp-page="/CSharp/Easy/Index">Easy</a>
                        <ul>
                            <li>
                                <a asp-page="/CSharp/Easy/Post1">Post 1</a>
                            </li>
                            <li>
                                <a asp-page="/CSharp/Easy/Post2">Post 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a asp-page="/CSharp/Advanced/Index">Advanced</a>
                        <ul>
                            <li>
                                <a asp-page="/CSharp/Advanced/Post1">Post 1</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a asp-action="Index" asp-controller="Java">Java</a>
                <ul>
                    <li>
                        <a asp-action="Index" asp-controller="EasyJava">Easy</a>
                        <ul>
                            <li>
                                <a asp-action="Post1" asp-controller="EasyJava">Post 1</a>
                            </li>
                            <li>
                                <a asp-action="Post2" asp-controller="EasyJava">Post 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="AdvancedJava">Advanced</a>
                        <ul>
                            <li>
                                <a asp-action="Post1" asp-controller="AdvancedJava">Post 1</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a asp-action="XssTest" asp-controller="Other">XSS Test</a>
            </li>
            <li>
                <a asp-action="Index" asp-controller="Home" asp-area="VisualBasic">Visual Basic</a>
                <ul>
                    <li>
                        <a asp-action="Index" asp-controller="Easy" asp-area="VisualBasic">Easy</a>
                        <ul>
                            <li>
                                <a asp-action="Sub" asp-controller="Easy" asp-area="VisualBasic">Sub Easy</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="More" asp-controller="Easy" asp-area="VisualBasic">More Easy</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Advanced" asp-area="VisualBasic">Advanced</a>
                    </li>
                </ul>
            </li>
            <li>
                <a asp-action="Index" asp-controller="Home" asp-area="JavaScript">JavaScript</a>
                <ul>
                    <li>
                        <a asp-action="Index" asp-controller="Easy" asp-area="JavaScript">Easy</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Advanced" asp-area="JavaScript">Advanced</a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        <a asp-page="/About">About</a>
    </li>
</ul>